version: '3'

services:
  jupyter:
    build: .
    environment:
      - DISPLAY=novnc:0
    depends_on:
      - novnc
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks

  novnc:
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1024
      - DISPLAY_HEIGHT=768
      - RUN_XTERM=no
    ports:
      - "8080:8080"